create database Gogo;
use Gogo;

create table cultural_locations (
	id int AUTO_INCREMENT PRIMARY KEY,
	name nvarchar(255),
   region nvarchar(255),
   image_url nvarchar(255),
   description text
);

create table cuisines (
	id int AUTO_INCREMENT PRIMARY KEY,
   name nvarchar(255),
   description text,
   image_url nvarchar(255),
   location_id int,
   CONSTRAINT fk_cuisines_location FOREIGN KEY (location_id) REFERENCES cultural_locations(id)
);

create table events (
	id int AUTO_INCREMENT PRIMARY KEY,
   name nvarchar(255),
   event_date Date,
   description text,
   cultural_location_id int,
   image_url nvarchar(255),
   CONSTRAINT fk_events_location FOREIGN KEY (cultural_location_id)  REFERENCES cultural_locations(id)
);

create table dishes (
   id int AUTO_INCREMENT PRIMARY KEY,
   name nvarchar(255),
   description text,
   image_url nvarchar(255),
   cuisines_id int,
   CONSTRAINT fk_dishes_cuisines FOREIGN KEY (cuisines_id) REFERENCES cuisines(id)   
 );
 
create table tours (
   id INT AUTO_INCREMENT PRIMARY KEY,
   name NVARCHAR(255),
   description TEXT,
   started_date DATE,
   completed_date DATE,
   price INT,
   image_url NVARCHAR(255),        
   schedule TEXT,                  
   organizer NVARCHAR(255),         
   cultural_location_id INT,
   CONSTRAINT fk_tour_location FOREIGN KEY (cultural_location_id) REFERENCES cultural_locations(id)
);

create table users (
   id INT AUTO_INCREMENT PRIMARY KEY,
   email NVARCHAR(255),
   username NVARCHAR(50),
   password NVARCHAR(255),
   fullname NVARCHAR(50),
   phone NVARCHAR(15),
   created_date DATE,
   image_url NVARCHAR(255)
);

create table bookings (
   id INT AUTO_INCREMENT PRIMARY KEY,
   user_id INT,
   tour_id INT,
   booking_date DATE,
   total_cost INT,
   status NVARCHAR(255),
   CONSTRAINT fk_user FOREIGN KEY (user_id) REFERENCES users(id),
   CONSTRAINT fk_tour FOREIGN KEY (tour_id) REFERENCES tours(id)
);

create table reviews (
   id int AUTO_INCREMENT PRIMARY KEY,
   detail text,
   rating int(5),
   review_date date,
   user_id int,
   CONSTRAINT fk_reviews_users FOREIGN KEY (user_id) REFERENCES users(id)
);

INSERT INTO cultural_locations (name, region, image_url, description) VALUES
("Ha Noi", "Northern Vietnam", "https://owa.bestprice.vn/images/destinations/uploads/trung-tam-thanh-pho-ha-noi-603da1f235b38.jpg", "Ha Noi, Vietnam’s capital, is a city where the past and present coexist harmoniously. Its ancient temples, such as the iconic Temple of Literature, stand alongside French colonial buildings, offering a blend of history and modernity. The Old Quarter, with its narrow streets and traditional shops, adds to the city’s charm. Visitors can also explore Hoan Kiem Lake, a serene space in the heart of the city, and the Ho Chi Minh Mausoleum, which honors the country's beloved leader. The city’s vibrant culture and rich history make it a must-visit destination for those exploring Northern Vietnam."), 
("Ha Long", "Northern Vietnam", "https://asiaholiday.com.vn/pic/Tour/Tour%20Du%20lich%20Ha%20Long%20(5)_2261_HasThumb.jpg", "Ha Long Bay, a UNESCO World Heritage Site, is one of Vietnam’s most famous natural wonders. Known for its emerald waters and thousands of towering limestone karsts and islands, the bay offers a spectacular landscape that captivates all who visit. Cruises through the bay provide a serene experience while exploring its hidden caves and grottoes. Whether by boat, kayak, or simply admiring the scenery from a vantage point, Ha Long is an unmissable destination for nature lovers and adventure seekers alike."), 
("Sa Pa", "Northern Vietnam", "https://media.baobinhphuoc.com.vn/upload/news/5_2023/c29efc89b1a8554f27a79a5bf6bdf6a0.jpg", "Sa Pa, nestled in the northern mountains of Vietnam, is a trekkers’ paradise. Its terraced rice fields and breathtaking views of Mount Fansipan, the highest peak in Southeast Asia, create a stunning backdrop for outdoor adventures. The region is also home to various ethnic minority villages, where visitors can learn about local traditions and cultures. Sa Pa’s cool climate and natural beauty make it an ideal escape for those looking to experience the tranquility of the highlands."), 
("Mai Chau", "Northern Vietnam", "https://mia.vn/media/uploads/blog-du-lich/mai-chau-hoa-binh-co-gi-1-1681688296.jpg", "Mai Chau is a peaceful valley surrounded by towering mountains in Northern Vietnam. Known for its lush landscapes and vibrant green rice paddies, it offers visitors an authentic experience with the local Thai ethnic groups, who offer homestays in traditional stilt houses. The area is ideal for cycling through bamboo forests, trekking, and experiencing rural life. With its serene atmosphere and natural beauty, Mai Chau is the perfect getaway from the hustle and bustle of the city."), 
("Ninh Binh", "Northern Vietnam", "https://cafefcdn.com/203337114487263232/2024/9/4/ninh-binh-2-17247693034201095070408-61-1725440596887-17254405970681798243927.jpg", "Ninh Binh, often called the “Halong Bay on land,” is a region renowned for its dramatic landscapes of limestone cliffs, caves, and rivers. Visitors can take a tranquil boat ride through Tam Coc, often referred to as ‘the Halong Bay of the rice paddies,’ and explore the caves and grottoes nestled between towering cliffs. Ninh Binh is also home to ancient temples and pagodas, such as the impressive Bai Dinh Pagoda. With its breathtaking scenery and rich history, Ninh Binh is a must-see destination for those exploring Northern Vietnam."), 
("Ha Giang", "Northern Vietnam", "https://vnmedia.vn/file/8a10a0d36ccebc89016ce0c6fa3e1b83/112023/ha_20231114082805.jpg", "Ha Giang, located in the far north of Vietnam, is a remote and rugged region known for its stunning mountainous landscapes. The Dong Van Karst Plateau, a UNESCO Global Geopark, features dramatic cliffs, deep valleys, and terraced fields that make it a favorite destination for motorbike tours. Ha Giang is also home to several ethnic minority communities, and visitors can explore their colorful markets and traditions. The region’s natural beauty, ethnic diversity, and off-the-beaten-path appeal make it one of Vietnam’s most unforgettable destinations."), 
("Da Nang", "Central Vietnam", "https://static-2.happynest.vn/storage/uploads/2024/06/15-dia-diem-du-lich-da-nang-dep-me-man-nam-2024_0.jpg", "Da Nang, a vibrant coastal city in Central Vietnam, offers a perfect blend of modernity and nature. It’s famous for its beautiful beaches, such as My Khe and Non Nuoc, which attract beach lovers and water sports enthusiasts. The city is home to iconic landmarks like the Dragon Bridge and the Marble Mountains, with their impressive caves and pagodas. Da Nang also serves as the gateway to the stunning Bana Hills, known for the Golden Bridge, a famous architectural marvel. The city’s blend of cultural attractions, natural beauty, and modern amenities makes it an exciting destination for travelers." ),
("Hoi An", "Central Vietnam", "https://images2.thanhnien.vn/528068263637045248/2023/4/4/hoi-an-1680591517857660432696.jpg", "Hoi An is a UNESCO World Heritage Site that captivates visitors with its well-preserved ancient town, where time seems to stand still. Known for its picturesque, lantern-lit streets, the town’s blend of traditional wooden architecture and vibrant tailor shops creates a charming atmosphere. The town’s culinary scene is equally rich, offering street food that mixes Chinese, Japanese, and Vietnamese influences. A must-visit is the iconic Japanese Covered Bridge, one of the town’s most famous landmarks. Hoi An is a perfect place for those seeking a mix of history, culture, and culinary experiences."), 
("Nha Trang", "Central Vietnam", "https://dulichseatravel.com/wp-content/uploads/2023/10/duong-tran-phu-nha-trang-2_1651556571.jpg", "Nha Trang is a beach lover's paradise located along the central coast of Vietnam, famous for its turquoise waters, coral reefs, and sandy beaches. The city’s coastline is dotted with luxury resorts, offering an ideal place for relaxation and water sports. Nha Trang is also known for its vibrant nightlife, with numerous bars, restaurants, and nightclubs. Beyond the beach, visitors can explore cultural attractions like the Po Nagar Cham Towers, a testament to the region's rich Cham heritage. Nha Trang is a perfect blend of natural beauty, modern amenities, and cultural exploration."), 
("Hue", "Central Vietnam", "https://hotelnikkohanoi.com.vn/wp-content/uploads/2023/04/ban-do-du-lich-hue-1.jpg", "Hue, the former imperial capital of Vietnam, is a city steeped in history and culture. Known for its grand citadel, the city’s ancient imperial palace and royal tombs offer a glimpse into the glory of the Nguyen Dynasty. The Perfume River, which runs through Hue, provides a serene setting for river cruises that reveal the city’s cultural and historical treasures. Hue is also home to beautiful pagodas and vibrant street markets. This historic city offers visitors a chance to immerse themselves in Vietnamese history, architecture, and royal heritage."), 
("Phong Nha", "Central Vietnam", "https://cdnmedia.baotintuc.vn/Upload/c2tvplmdloSDblsn03qN2Q/files/2023/03/07/du-lich-phong-nha-732023.jpg", "Phong Nha, located in Quang Binh province, is a must-visit for adventure lovers and nature enthusiasts. It is home to the world’s largest cave, Son Doong, and boasts one of the most spectacular cave systems in the world. The Phong Nha-Kẻ Bàng National Park is a UNESCO World Heritage Site known for its stunning karst landscapes, underground rivers, and rich biodiversity. Adventurers can explore vast caves, hike through lush forests, or take boat rides on the river. Phong Nha offers an unforgettable experience for those who enjoy nature and exploration."), 
("Da Lat", "Central Vietnam", "https://agotourist.com/wp-content/uploads/2021/10/thanh-pho-da-lat-2.jpg", "Da Lat, known as the ‘City of Eternal Spring,’ is a romantic mountain retreat that draws visitors with its cool weather, beautiful flower gardens, and French colonial architecture. The city is surrounded by lush pine forests, serene lakes, and cascading waterfalls, making it a popular destination for nature lovers. Da Lat also offers a range of adventure sports, including canyoning, hiking, and mountain biking. Its charming atmosphere, pleasant climate, and picturesque landscapes make it a perfect destination for a relaxing getaway or outdoor activities."), 
("Phu Yen", "Central Vietnam", "https://ohdidi.vn/uploads/members/uyen.vo/du%20l%E1%BB%8Bch%20phu%20yen%20mua%20nao%20d%E1%BA%B9p/du-lich-phu-yen-mua-nao-dep%202.png", "Phu Yen, an emerging destination in Central Vietnam, offers unspoiled beaches, rugged cliffs, and scenic coastal landscapes. It is a haven for nature lovers seeking tranquility and a slower pace of life. Phu Yen is home to the iconic Da Dia Reef, where unique black stone formations create a striking contrast against the sea. The region also offers picturesque fishing villages and remote beaches, perfect for those looking to escape the crowds and experience Vietnam’s natural beauty in peace. Phu Yen is ideal for those wanting to explore Vietnam off the beaten path." ),
("Ho Chi Minh City", "Southern Vietnam", "https://www.visithcmc.vn/uploads/0000/6/2021/08/22/hcmc-1120046774-1.jpg", "Ho Chi Minh City, Vietnam's bustling economic hub, offers a dynamic blend of historical landmarks and modern development. The War Remnants Museum and Cu Chi Tunnels offer deep insights into Vietnam’s wartime history, while modern skyscrapers dominate the skyline. The city is a melting pot of cultures, where visitors can experience a lively atmosphere through its vibrant street markets, bustling nightlife, and ever-growing craft beer scene. Known for its food culture, Ho Chi Minh City is home to world-famous Vietnamese street food such as pho and banh mi. It’s the perfect destination for urban explorers looking to experience both history and modernity in one place."), 
("Binh Thuan", "Southern Vietnam", "https://mia.vn/media/uploads/blog-du-lich/du-lich-binh-thuan-01-1695999943.jpg", "Binh Thuan, located along the southeastern coast of Vietnam, is famous for its tranquil beaches, most notably those in Mui Ne. The area is also known for its stunning red sand dunes, where visitors can try sandboarding or simply enjoy the panoramic desert-like landscapes. Binh Thuan’s peaceful atmosphere makes it a perfect destination for those looking for a quiet retreat. The region is also renowned for its dragon fruit plantations, which are a key part of the local economy. Additionally, Binh Thuan holds cultural significance with its Cham heritage, including ancient temples and artifacts that reflect its rich history."), 
("Con Dao", "Southern Vietnam", "https://media-cdn-v2.laodong.vn/Storage/NewsPortal/2022/9/24/1096833/Hon-Bay-Canh---Yeudu.jpg", "Con Dao is an idyllic archipelago of pristine islands, celebrated for its clear turquoise waters and vibrant coral reefs, making it an excellent destination for snorkeling and diving. Visitors can explore untouched beaches and enjoy the peaceful surroundings, far from the bustling crowds of mainland Vietnam. Con Dao also has historical significance, with the infamous Con Dao Prison providing a glimpse into the harsh conditions endured by political prisoners during Vietnam’s colonial past. With its natural beauty and rich history, Con Dao offers a unique blend of relaxation and exploration for those seeking tranquility and historical discovery."), 
("Phu Quoc", "Southern Vietnam", "https://ik.imagekit.io/tvlk/blog/2024/08/thoi-tiet-phu-quoc-7.jpg?tr=dpr-2,w-675", "Phu Quoc, often referred to as Pearl Island, is renowned for its stunning white-sand beaches, crystal-clear waters, and lush national parks. The island offers a wide range of activities, from snorkeling and trekking to relaxing at luxury resorts. The vibrant night markets on the island provide an authentic experience where visitors can sample fresh seafood and local delicacies. Phu Quoc is also home to some of Vietnam's most picturesque beaches, including Sao Beach and Long Beach, where travelers can unwind amidst nature. Ideal for both adventure seekers and those in search of relaxation, Phu Quoc offers the perfect tropical getaway."), 
("Can Tho", "Southern Vietnam", "https://vnexplores.vn/uploads/0000/6/2024/09/01/cantho.jpg", "Can Tho, located in the heart of the Mekong Delta, is famous for its lively floating markets, such as Cai Rang, where locals trade fresh produce from boats, offering a unique glimpse into river life. Visitors can take boat tours to explore the intricate network of rivers, canals, and lush orchards that define the delta. The region is also known for its traditional rural charm, where travelers can visit local villages, experience homestays, and witness agricultural practices. Can Tho’s vibrant atmosphere, combined with its scenic beauty and rich cultural heritage, makes it a top destination for anyone interested in rural Vietnamese life and the Mekong Delta."), 
("Chau Doc", "Southern Vietnam", "https://cdn.tgdd.vn/Files/2022/03/29/1422960/kinh-nghiem-du-lich-chau-doc-tat-tan-tat-tu-a-z-202203292333393564.jpg", "Chau Doc, located near the Cambodian border, is a culturally diverse region where Vietnamese, Khmer, and Cham cultures converge. Known for its natural beauty, Chau Doc boasts landmarks such as Sam Mountain, which offers panoramic views of the surrounding countryside, and the Tra Su Cajuput Forest, a peaceful sanctuary for birdwatching and boating. The region is also famous for its floating villages, where local communities live on the water and rely on fishing for their livelihood. Chau Doc is a fascinating destination for travelers interested in culture, nature, and the unique way of life in the Mekong Delta." );

INSERT INTO cuisines (name, description, image_url, location_id) VALUES
("Pho", "A famous Vietnamese noodle soup made with a flavorful broth, rice noodles, herbs, and typically beef (pho bo) or chicken (pho ga). It\'s often served with fresh herbs, bean sprouts, lime, and chili on the side.", "https://dienmaynewsun.com/wp-content/uploads/2019/08/cong-thuc-nuoc-dung-pho.webp", 1),
("Banh Mi", "A Vietnamese sandwich consisting of a baguette filled with a variety of ingredients like meats (usually pork, chicken, or beef), pickled vegetables, cilantro, cucumber, and spicy condiments. It combines French influences with Vietnamese flavors.", "https://i.ytimg.com/vi/h5eq9yfMAKs/hq720.jpg?sqp=-oaymwEhCK4FEIIDSFryq4qpAxMIARUAAAAAGAElAADIQj0AgKJD&rs=AOn4CLDmoMZWzKJ_6kKQtcO7xgKZXrBGNQ", 2),
("Com Tam", "Known as broken rice. This dish is served with grilled pork (often ribs or shredded pork), but can also include fried egg, pickled vegetables, and a side of fish sauce, making it a flavorful and hearty meal.", "https://cafebiz.cafebizcdn.vn/162123310254002176/2022/12/7/com-tam-suon-bi-cha-trung-anh-hoa-quynh-nguyen-1670317945936565526419-1670385940206-16703859407121546487016-1670395722685-16703957227611562343004.jpg", 3),
("Bun Bo Hue", "A spicy, aromatic beef noodle soup originating from Hue, Vietnam. It features a rich broth made with lemongrass and chili, served with rice noodles, tender beef, and sometimes pork, accompanied by fresh herbs.", "https://static.vinwonders.com/production/bun-bo-hue-ngon-o-sai-gon-2.jpg", 3),
("Cao Lau", "A signature dish from Hoi An, consisting of thick noodles served with slices of pork, crispy croutons, fresh herbs, and a small amount of broth. The noodles are made with water from a specific well in Hoi An, giving them a unique texture.", "https://cdn.tgdd.vn/2021/12/CookDishThumb/cao-lau-la-gi-nguon-goc-cao-lau-cao-lau-va-mi-quang-khac-nhau-thumb-620x620.jpg", 5),
("Com Ga", "A Vietnamese chicken rice dish, typically made with steamed or boiled chicken served with fragrant rice cooked in chicken broth, accompanied by fresh vegetables, herbs, and often a side of dipping sauce.", "https://static.vinwonders.com/2023/02/com-ga-da-nang-2.jpeg", 1),
("Mi Quang", "A noodle dish from Quang Nam province, featuring wide rice noodles served with a small amount of broth, shrimp, pork, or chicken, and topped with peanuts, herbs, and crispy rice crackers. It\'s typically enjoyed with a strong, savory flavor.", "https://hoianheritage.net/uploads/trao-doi-chuyen-nganh/2022_08/mi-quang-hoi-an-ngon.jpg", 7),
("Banh Xeo", "Vietnamese savory pancakes made with rice flour, turmeric, and coconut milk. They are filled with a variety of ingredients such as shrimp, pork, bean sprouts, and onions, and are often eaten wrapped in lettuce with herbs and dipped in fish sauce.", "https://www.andy-cooks.com/cdn/shop/articles/20240406030532-andy-20cooks-20-20banh-20xeo.jpg?v=1712382159", 8),
("Bun Cha", "A grilled pork dish served with rice noodles, fresh herbs, and a sweet-sour dipping sauce. The pork is grilled and served alongside crispy fried pork meatballs. It is a popular dish in Hanoi.", "https://media-cdn-v2.laodong.vn/storage/newsportal/2023/7/1/1211359/Bun-Cha-Quat.jpeg?w=800&crop=auto&scale=both", 6),
("Xoi", "A traditional sticky rice dish often eaten for breakfast or as a snack. It can be served with a variety of toppings, such as mung beans, fried shallots, shredded coconut, or pork.", "https://beptruong.edu.vn/wp-content/uploads/2015/11/xoi-xeo-ha-noi.jpg", 10),
("Banh Beo", "Small, round rice cakes topped with shrimp, fried onions, and herbs, often served with fish sauce. It\'s a popular snack or appetizer in central Vietnam.", "https://static.vinwonders.com/2022/10/banh-beo-da-nang-1.jpg", 11),
("Bun Rieu", "A Vietnamese noodle soup made with a tomato-based broth, rice noodles, and crab or pork. It\'s typically topped with fried tofu, shrimp, and fresh herbs.", "https://i.ytimg.com/vi/C1P1Cw9J1-I/hq720.jpg?sqp=-oaymwEhCK4FEIIDSFryq4qpAxMIARUAAAAAGAElAADIQj0AgKJD&rs=AOn4CLD7gErv1KKy_4KmD2kg-CboPePusQ", 7),
("Goi Cuon", "Vietnamese spring rolls made with rice paper and filled with shrimp, fresh herbs, rice noodles, and lettuce. They are typically served with a peanut or hoisin-based dipping sauce.", "https://upload.wikimedia.org/wikipedia/commons/0/01/Goi_Cuon_VN.jpg", 13),
("Hu Tieu Nam Vang", "A noodle soup that originated from Phnom Penh, Cambodia, but is widely popular in southern Vietnam. It consists of clear broth, rice noodles, and various meats, such as pork, shrimp, and sometimes organ meats.", "https://danangtoiyeu.com/wp-content/uploads/2024/04/hu-tieu-nam-vang-da-nang-4.png", 2),
("Cha Ca", "A Hanoi specialty made from marinated fish (usually catfish or other white fish) grilled or pan-fried and served with noodles, herbs, and peanuts, often topped with a rich turmeric-based sauce.", "https://anbieneatery.com/wp-content/uploads/2021/06/IMG_0054-e1629126304958.jpg", 15),
("Nom Hoa Chuoi", "A type of Vietnamese salad made with banana flowers, herbs, and often mixed with shredded chicken or pork. It\'s typically dressed with fish sauce and lime, giving it a tangy and refreshing flavor.", "https://i-giadinh.vnecdn.net/2021/10/13/nomhoachuoi-1634112383-3141-1634112478.png", 5),
("Banh Cuon", "Steamed rice rolls filled with a savory mixture of minced pork, mushrooms, and onions. The rolls are often served with fried shallots, fresh herbs, and a dipping sauce made with fish sauce.", "https://dienmaynewsun.com/wp-content/uploads/2023/05/banh-cuon-ngon.jpg", 10),
("Bun Bo Cuon La Lot", "A dish made with grilled beef wrapped in betel leaves, then served with rice noodles, fresh herbs, and a side of fish sauce. The betel leaves give the meat a unique, aromatic flavor.", "https://beptruong.edu.vn/wp-content/uploads/2018/05/bo-nuong-la-lot.jpg", 6),
("Che", "A Vietnamese dessert made from a variety of ingredients like beans, tapioca pearls, fruits, and sweetened coconut milk. It can be served hot or cold and is often enjoyed as a refreshing treat.", "https://danviet.mediacdn.vn/296231569849192448/2021/12/2/che-hoi-an-1638414830708721416189.jpg", 8);

INSERT INTO events (name, event_date, description, cultural_location_id, image_url) VALUES
("Hue Festival", "2024-11-20", "Hue Festival is one of Vietnam's most spectacular cultural events, held every two years in the historic city of Hue. This grand celebration brings together elements of Vietnam’s imperial past, featuring reenactments of Nguyễn Dynasty rituals such as royal processions and banquets. Visitors can enjoy performances of Nha Nhac, the court music of Hue, which has been recognized as UNESCO intangible cultural heritage. The festival is a melting pot of traditional and contemporary art, with theater, dance, and fashion shows held across the city. Artisans from all over Vietnam display their crafts, from intricate embroidery to pottery, creating a vibrant market atmosphere. The Perfume River becomes a stage for mesmerizing light shows and boat performances, while the ancient citadel glows with colorful illuminations. Food lovers will delight in the festival's culinary offerings, which showcase Hue's renowned royal cuisine and street food. The event also serves as a platform for international cultural exchange, with performances from various countries. With its blend of history, culture, and entertainment, Hue Festival attracts visitors of all ages and interests.", 10, "https://media.techcity.cloud/hue/2024/07/Tuan-le-Festival-Hue-2022.jpg"),
("Lim Festival", "2024-11-25", "The Lim Festival is a unique cultural event held annually in the Kinh Bắc region, renowned for its soulful Quan Họ folk singing. Recognized as a UNESCO intangible cultural heritage, these traditional love duets are performed by men and women dressed in elegant costumes, creating an unforgettable auditory experience. The festival also features a wide range of traditional games such as human chess, tug-of-war, and bamboo swinging, providing entertainment for all ages. Visitors can explore the Lim Pagoda, a spiritual site linked to the origins of Quan Họ singing. Additionally, the festival is a culinary delight, offering local specialties such as rice cakes and honey-glazed fruits. Pilgrims and tourists alike gather to experience the harmonious blend of spirituality, tradition, and festivity. The Lim Festival is not just an event but a celebration of Vietnam’s enduring cultural heritage, bringing together communities in a shared appreciation of art and history. It offers a unique insight into the lifestyle and traditions of northern Vietnam, making it a must-see for cultural enthusiasts. The warm hospitality of the locals adds to the festival’s charm, ensuring an unforgettable experience.", 1, "https://media-cdn-v2.laodong.vn/storage/newsportal/2024/2/19/1305522/Hoi-Lim.jpg"),
("Ha Noi International Film Festival", "2024-11-21", "The Ha Noi International Film Festival is a prestigious event that celebrates the art and craft of cinema. Held in the capital city of Vietnam, this festival gathers filmmakers, actors, and industry professionals from around the world. It showcases a diverse selection of films, including groundbreaking Vietnamese productions and internationally acclaimed works. The festival’s program includes screenings, workshops, and panel discussions, providing an engaging platform for storytelling and cinematic innovation. Aspiring filmmakers can attend masterclasses conducted by renowned directors and screenwriters, offering invaluable insights into the creative process. In addition to the screenings, the festival hosts an awards ceremony to honor excellence in categories such as Best Film, Best Actor, and Best Director. It also highlights Vietnam’s unique cultural narratives, fostering an appreciation for the country's cinematic identity. The event attracts a global audience, promoting cultural exchange and collaboration. Whether you’re a cinephile or a casual viewer, the Ha Noi International Film Festival offers a dynamic, enriching experience that celebrates the power of storytelling.", 1, "https://media.vov.vn/sites/default/files/styles/large/public/2024-07/ntt_7815_0.jpg"),
("Hung Kings'Death Anniversary", "2024-11-22", "The Hung Kings'Death Anniversary is one of Vietnam's most important national holidays, deeply rooted in the nation's history and traditions. This event commemorates the legendary Hung Kings, believed to be the founders of Vietnam and its earliest dynasties. The main ceremonies take place at the Hung Temple complex in Phu Tho Province, where pilgrims gather to pay respects and offer incense. Elaborate parades featuring traditional costumes and music create a festive atmosphere, while cultural performances bring legends of the Hung Kings to life. Visitors can also enjoy traditional games such as tug-of-war, bamboo dancing, and folk wrestling, which highlight the community spirit of the event. The celebration includes culinary offerings of sticky rice cakes (Bánh Chưng and Bánh Dày), symbolizing gratitude and unity. The event fosters a sense of pride and belonging, drawing people from across the country to honor their shared heritage. It is not only a tribute to the ancestors but also a celebration of Vietnamese resilience and cultural identity. The Hung Kings's Death Anniversary serves as a reminder of Vietnam's long and storied past, making it a meaningful experience for locals and tourists alike.", 1, "https://images.baodantoc.vn/uploads/2021/Th%C3%A1ng%202/Ng%C3%A0y_24/Thanh/cac-nghi-le-chinh-trong-ngay-gio-to-hung-vuong.jpg"),
("Hoi An Lantern Festival", "2024-11-26", "The Hoi An Lantern Festival is a magical celebration that takes place every full moon in the enchanting town of Hoi An. During the festival, the town transforms into a kaleidoscope of colors, with vibrant lanterns adorning the streets and floating gently on the Thu Bon River. Visitors can participate in the tradition of releasing paper lanterns into the river, accompanied by prayers for health, happiness, and prosperity. The festival is a feast for the senses, featuring traditional music and dance performances as well as poetry readings that reflect the town’s rich cultural history. Local artisans demonstrate their crafts, allowing visitors to learn about lantern-making and other traditional skills. The streets are closed to motorized traffic, creating a peaceful ambiance where visitors can stroll and soak in the atmosphere. Food vendors line the streets, offering delicious Vietnamese delicacies like Cao Lầu and fresh spring rolls. The festival also includes ceremonies at the town’s ancient temples, adding a spiritual dimension to the event. The Hoi An Lantern Festival is more than a visual spectacle—it’s a journey into Vietnam’s cultural and spiritual traditions, offering an unforgettable experience for all who attend.", 8, "https://data.agatetravel.com/images/photogallery/2020/hoi-an-lantern-festival-vietnam.jpg"),
("Da Nang International Fireworks Festival", "2024-06-01", "Teams from various countries compete in spectacular fireworks displays, set to music and lighting, along the Han River.", 7, "https://www.pullman-danang.com/wp-content/uploads/sites/86/2019/04/AM12-Ng%C3%A0y-294.jpg"),
("Tay Son Festival", "2024-02-01", "The Tay Son Festival is a grand celebration held to commemorate the heroic uprising led by Emperor Quang Trung and the victory over foreign invaders in the 18th century. The festival takes place in Tay Son District, Binh Dinh Province, and includes reenactments of historic battles, paying tribute to the bravery and strategic brilliance of the emperor. Visitors can witness dynamic martial arts demonstrations, showcasing Binh Dinh's famous combat techniques and traditional weaponry. The rhythmic beats of the Tay Son drumming performances add a powerful and invigorating energy to the festivities, drawing large crowds from near and far. The festival also features cultural activities such as lion dancing, traditional games, and local art exhibitions. Pilgrims and locals gather at the Tay Son Museum and the Emperor Quang Trung Temple to offer incense and pay respects to the national hero. Food stalls line the event area, offering regional delicacies and drinks for attendees to savor. The Tay Son Festival is not only a commemoration of Vietnam’s historical triumphs but also a vibrant celebration of its cultural heritage, making it a must-see for history enthusiasts and travelers.", 4, "https://image.sggp.org.vn/w1000/Uploaded/2024/aopsvhu/2022_02_05/tayson_plwy.jpg.webp"),
("Whale Festival", "2024-08-01", "The Whale Festival is a deeply spiritual and cultural event held annually by fishing communities along Vietnam’s coast. The festival honors the whale, revered as the sacred guardian of the sea who protects fishermen and ensures safe voyages. The event begins with solemn ceremonies at the local temple, where offerings of fruits, flowers, and incense are made to the whale deity. Vibrant processions feature elaborately decorated boats, carried by fishermen dressed in traditional attire, parading through the village and along the shoreline. Traditional music and chants accompany the rituals, creating a solemn yet festive atmosphere. The festival also includes cultural performances such as folk dances and sea shanties that celebrate the lives and traditions of the fishing community. Visitors can enjoy freshly caught seafood prepared in various local styles, adding a culinary highlight to the event. The Whale Festival is not only a religious occasion but also a time for unity, gratitude, and cultural preservation, making it an unforgettable experience for both locals and tourists.", 6, "https://bcp.cdnchinhphu.vn/334894974524682240/2023/2/2/dsc07237-16753269791211613410312.jpg"),
("Whale Festival", "2024-08-01", "The Whale Festival, known as Le Nghinh Ong, is a highly anticipated annual event celebrated by Vietnam’s coastal fishing communities. This deeply spiritual festival pays homage to the whale, regarded as the guardian of the sea and a symbol of protection and good fortune for fishermen. The celebrations commence with an elaborate ceremony at the local temple, where offerings of flowers, incense, fruits, and seafood are presented to express gratitude and pray for safe and prosperous fishing voyages. The highlight of the festival is the grand procession, where a beautifully decorated boat carrying a whale statue is paraded through the village streets and along the waterfront, accompanied by traditional music and chants. Locals, dressed in vibrant ceremonial attire, participate with great enthusiasm, while cultural performances such as lion dances, folk songs, and sea-themed shanties add to the festivities. Visitors can also witness unique maritime traditions and sample freshly prepared seafood delicacies. Beyond its religious significance, the Whale Festival is a joyful celebration of community spirit, cultural heritage, and the deep connection between Vietnam’s coastal people and the sea.", 6, "https://bcp.cdnchinhphu.vn/334894974524682240/2023/2/2/dji0619-16753265912202046913869.jpg"),
("Da Lat Flower Festival", "2024-01-01", "The Da Lat Flower Festival is a stunning celebration of the vibrant flower culture that defines the charming highland city of Da Lat. Held every two years, the festival transforms the city into a floral wonderland with elaborate flower displays, artistic arrangements, and themed gardens. Visitors can stroll through flower exhibitions showcasing local blooms such as roses, orchids, and hydrangeas, as well as exotic species cultivated in Da Lat’s temperate climate. The festival features colorful parades with floats adorned in flowers, accompanied by performers in creative costumes. Cultural performances, music concerts, and art exhibitions add to the festive atmosphere, offering entertainment for all ages. The event also highlights Da Lat's agricultural heritage, with stalls promoting locally grown fruits, vegetables, and specialty products such as coffee and tea. Visitors can participate in gardening workshops, learn about sustainable flower farming, and take home unique floral souvenirs. The Da Lat Flower Festival is more than just a visual treat—it is a celebration of nature, creativity, and the city's unique identity, drawing visitors from across the globe.", 5, "https://bazantravel.com/cdn/medias/uploads/36/36342-vuon-hoa-da-lat-bazan-travel-1.jpg"),
("First Full Moon Festival", "2024-01-15", "The First Full Moon Festival, known as Tet Nguyen Tieu in Vietnam, is a spiritually significant event marking the first full moon of the lunar year. It is a time for families to come together and pray for health, happiness, and prosperity in the year ahead. Temples across the country are adorned with vibrant decorations as devotees offer incense, fruits, and other symbolic items to the deities. The festival is characterized by traditional rituals, including the recitation of Buddhist sutras and ceremonies to honor ancestors. In some regions, lion dances and cultural performances enliven the atmosphere, while others organize processions carrying lanterns symbolizing enlightenment and good fortune. Special vegetarian dishes are prepared during this festival, as many observe it as a day of mindfulness and purity. Communities also host poetry readings and calligraphy demonstrations, reflecting Vietnam's deep cultural and spiritual roots. The First Full Moon Festival is a harmonious blend of religious devotion, cultural heritage, and familial bonds, offering a meaningful start to the lunar year.", 3, "https://afamilycdn.com/2018/3/1/15-15199205380961830948326.jpg"),
("Fish Worship Festival", "2024-03-01", "The Fish Worship Festival, known locally as Le Cau Ngu, is a vibrant and deeply spiritual event celebrated by fishing communities in central Vietnam. Held to honor the sea gods and pay tribute to the sacred whale, the festival reflects fishermen’s gratitude for past blessings and prayers for bountiful catches and peaceful seas. The celebration begins with solemn rituals at local temples, where offerings of fruits, flowers, and cooked seafood are presented. Following the rituals, colorful processions featuring decorated boats and traditional music set sail to bless the waters. The festival also includes folk games, water-based competitions, and performances of traditional songs that tell tales of maritime legends and the hardships of fishermen. Visitors are welcomed to taste freshly caught seafood prepared in various regional styles, adding a culinary highlight to the experience. Beyond its spiritual essence, the Fish Worship Festival serves as a vibrant showcase of Vietnam’s coastal culture, uniting communities and offering a memorable experience for all attendees.", 6, "https://baokhanhhoa.vn/file/e7837c02857c8ca30185a8c39b582c03/dataimages/201905/original/images5362312_caungu_3.jpg"),
("Mid-Autumn Festival", "2024-09-15", "The Mid-Autumn Festival, also known as Tet Trung Thu, is one of Vietnam’s most beloved cultural celebrations, especially cherished by children. Taking place on the 15th day of the eighth lunar month, the festival is marked by the glowing beauty of lanterns lighting up streets and homes across the country. Families gather to share mooncakes, a traditional pastry symbolizing reunion, and fruits arranged in artistic displays. The festival is steeped in folklore, with stories of the Moon Lady (Hang Nga) and the Moon Boy (Cuội) enchanting both young and old. Children enjoy lively parades featuring lion dances, while traditional games such as tug-of-war and blindfolded clay pot breaking bring communities together in joy. Many towns host cultural performances, including singing and dancing, adding to the festive atmosphere. The Mid-Autumn Festival is not only a time to celebrate the harvest and honor the moon but also an occasion to express love and gratitude within families, creating cherished memories for generations.", 1, "https://images.vietnamtourism.gov.vn/vn/images/Quatrungthu.jpg");

INSERT INTO dishes (name, description, image_url, cuisines_id) VALUES
("Pho Bo", "A Vietnamese beef noodle soup served with rice noodles in a rich, flavorful broth, typically garnished with herbs, bean sprouts, and lime.", "https://duonggiahotel.vn/wp-content/uploads/2023/09/quan-pho-da-nang.jpg", 1),
("Banh Mi Thit Nuong", "A Vietnamese sandwich with grilled pork, pickled vegetables, and cilantro in a French baguette.", "https://kvi.vn/Uploads/786/images/file_restaurant_photo_nfos_16608-a5edadfe-220818150324.jpg", 2),
("Com Tam Suon", "A popular Vietnamese dish with broken rice, grilled pork chops, pickled vegetables, and a side of fish sauce.", "https://bigtop.vn/wp-content/uploads/2022/11/Com-Tam-Suon-Cong-3.jpg", 3),
("Bun Bo Hue", "A spicy beef noodle soup with lemongrass, chili, and tender beef slices, originating from the city of Hue.", "https://bizweb.dktcdn.net/100/442/328/files/bun-bo-hue-dac-san-dan-da-lam-say-long-biet-bao-thuc-khach-4.jpg?v=1638937219225", 3),
("Cao Lau Hoi An", "A unique noodle dish from Hoi An, featuring thick noodles, grilled pork, crispy croutons, and fresh herbs.", "https://statics.vinpearl.com/cao-lau-hoi-an-01_1631078817.jpg", 5),
("Ga Nuong Mat Ong", "Grilled chicken glazed with honey, served with rice and fresh vegetables.", "https://amthucvanho.com.vn/wp-content/uploads/2019/12/lam-ga-nuong-mat-ong-thom-nuc-mui-cho-dem-giang-sinh-am-ap.jpg", 1),
("Mi Quang Tom", "A noodle dish from Quang Nam with a small amount of broth, shrimp, herbs, and crispy rice crackers.", "https://helenrecipes.com/wp-content/uploads/2021/05/Screenshot-2021-05-31-142423-1024x576.png", 7),
("Banh Xeo Sai Gon", "Vietnamese savory pancakes made with rice flour and turmeric, filled with shrimp, pork, and bean sprouts, served with lettuce and herbs.", "https://static.vinwonders.com/production/banh-xeo-sai-gon-banner.jpg", 8),
("Bun Cha Ha Noi", "Grilled pork served with rice noodles, herbs, and a dipping sauce, popular in Hanoi.", "https://thenguyen.vn/files/products/product_1831/bun-cha-ha-noi-chi-lay-ba-roi.jpg", 6),
("Che Ba Mau", "A traditional Vietnamese dessert with layers of green mung bean, red beans, and coconut milk, served cold.", "https://takestwoeggs.com/wp-content/uploads/2021/09/Che%CC%80-Ba-Ma%CC%80u-Vietnamese-three-colored-dessert-Takestwoeggs-Final-SQ.jpg", 8),
("Nom Ga", "A refreshing Vietnamese salad made with shredded chicken, banana flowers, herbs, and lime.", "https://giadinh.mediacdn.vn/296230595582509056/2022/11/7/nom-ga-xe-phay-1667791826652-1667791826978214972110.jpg", 5),
("Cha Ca La Vong", "A famous Hanoi dish with grilled fish served with vermicelli, fresh herbs, and a turmeric-based sauce.", "https://icdn.24h.com.vn/upload/4-2022/images/2022-12-01/1669861237-che1baa3cc3a1lc483ng-1669563905610-166956390586391225552-width680height454.jpg", 15),
("Banh Cuon Ha Noi", "Steamed rice rolls filled with minced pork, mushrooms, and herbs, topped with fried shallots and served with fish sauce.", "https://cdn.attractionsvietnam.com/uploads/2023/12/quan-banh-cuon-hanoi.jpg", 10),
("Bun Rieu Cua", "A Vietnamese noodle soup made with a crab-based broth, rice noodles, and topped with fried tofu and shrimp.", "https://i.ytimg.com/vi/C1P1Cw9J1-I/maxresdefault.jpg", 7);

INSERT INTO tours (name, description, started_date, completed_date, price, image_url, schedule, organizer, cultural_location_id) VALUES 
("Hanoi City Exploration", "A 3-day tour exploring Hanoi\'s rich history, culture, and landmarks such as Hoan Kiem Lake, the Old Quarter, and the Temple of Literature.", "2024-12-20", "2024-12-25", 6800000, "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/1b/33/f7/12/caption.jpg?w=1200&h=700&s=1", "Day 1: Arrival and city exploration, Day 2: Historical sites and local cuisine, Day 3: Free exploration and departure", "Ha Noi Tours Co.", 1),
("Hanoi Night Market Adventure", "Experience the vibrant night markets of Hanoi, where you can shop for local crafts, try street food, and explore the bustling Old Quarter.", "2024-12-20", "2024-12-25", 2000000, "https://cdn.vietnamisawesome.com/wp-content/uploads/2023/04/hanoi-night-market-2-1024x768.jpeg", "Evening: Explore night markets and enjoy street food, Night: Visit local bars and cafes", "Hanoi Nightlife Adventures", 1),
("Ho Chi Minh Mausoleum Tour", "A half-day tour to visit the Ho Chi Minh Mausoleum and learn about Vietnam\'s history and revolutionary leader.", "2024-12-01", "2024-12-07", 1500000, "https://c.foc.info/images/2019/05/960-ho-chi-minh-mausoleum-1557299245.jpg", "Morning: Cu Chi Tunnels exploration, Afternoon: Lunch and history museum visit", "Saigon Heritage Tours", 1), 
("Ha Long Bay Cruise", "A day tour with a boat cruise through Ha Long Bay, visiting limestone islands and caves, perfect for nature lovers.", "2024-12-22", "2024-12-26", 12000000, "https://www.halonghub.com/wp-content/uploads/2022/06/HalongHub-HeroHome.jpg", "Day 1: Cruise through limestone islands, Day 2: Explore Surprise Cave and Titop Island", "Ha Long Bay Cruises Co.", 2),
("Ha Long Bay Kayaking", "Experience the beauty of Ha Long Bay up close with a kayaking tour through its clear waters and limestone formations.", "2024-12-26", "2024-12-28", 8000000, "https://hanoiexploretravel.com/wp-content/uploads/2020/08/kayaking-at-luon-cave.jpg", "Day 1: Kayak through Luon Cave, Day 2: Visit Ba Hang fishing area", "Adventure Ha Long Tours", 2),
("Ha Long Fishing Village Visit", "A unique tour to visit the floating fishing villages of Ha Long Bay, learn about the local way of life, and enjoy fresh seafood.", "2024-12-01", "2024-12-05", 10000000, "https://statics.vinpearl.com/cua-van-floating-village-9_1677604968.jpg", "Day 1: Visit Cua Van Fishing Village, Day 2: Enjoy seafood lunch on floating houses", "Local Ha Long Experiences", 2),
("Sa Pa Trekking Tour", "A 2-day trekking tour through Sa Pa\'s terraced rice fields and ethnic minority villages, with stunning views of Mount Fansipan.", "2024-12-20", "2024-12-25", 7500000, "https://trekking-camping.com/wp-content/uploads/2021/02/Sapa.jpg", "Day 1: Trek through rice fields, Day 2: Visit Fansipan Base Camp and local villages", "Sa Pa Trekking Co.", 3),
("Sa Pa Homestay Experience", "Stay with a local ethnic minority family in Sa Pa, learn about their culture, and enjoy traditional meals.", "2024-12-24", "2024-12-27", 6000000, "https://sapanomad.com/wp-content/uploads/Experience-in-a-homestay-experience.jpg", "Day 1: Meet the host family, Day 2: Explore local markets and culture", "Sa Pa Cultural Homes", 3),
("Sa Pa Cultural Exploration", "Explore the rich cultures of Sa Pa\'s hill tribes with a guided tour to their villages and markets.", "2024-12-01", "2024-12-05", 5000000, "https://vietasiatravel.com/uploads/VietNam/Sa-pa/sapa5.jpg", "Day 1: Visit tribal villages, Day 2: Explore local markets and crafts", "Hill Tribe Tours Sa Pa", 3),
("Mai Chau Valley Tour", "A relaxing 1-day tour through the peaceful Mai Chau Valley, visiting Thai ethnic villages and enjoying local homestay experiences.", "2024-12-22", "2024-12-26", 4000000, "https://izitour.com/media/ckeditor/mai-chau-best-time-to-visit_2023-07-03_631.webp", "Day 1: Visit Thai villages, Day 2: Relax in Mai Chau Valley", "Mai Chau Explorer", 4),
("Mai Chau Cycling Tour", "A guided cycling tour through Mai Chau\'s bamboo forests and scenic countryside, perfect for nature and adventure enthusiasts.", "2024-12-25", "2024-12-27", 3000000, "https://authentiktravel.com/media/ckeditor/mai-chau-bike.jpg", "Day 1: Cycle through bamboo forests, Day 2: Explore scenic countryside", "Mai Chau Adventure", 4),
("Mai Chau Traditional Cuisine Tour", "Indulge in Mai Chau\'s traditional Thai dishes, including sticky rice, grilled meats, and herbal teas, on this food-focused tour.", "2024-11-28", "2024-12-02", 3500000, "https://maichauhideaway.com/Data/Sites/1/media/blog/am-thuc-tay-bac-maichauhideaway/com-lam-maichauhideaway.com.jpg", "Day 1: Experience Thai cooking, Day 2: Explore local markets", "Mai Chau Culinary Tours", 4),
("Tam Coc Boat Tour", "Take a scenic boat ride through the river and rice fields of Tam Coc, surrounded by dramatic limestone mountains.", "2024-12-21", "2024-12-27", 5000000, "https://hanoiexploretravel.com/wp-content/uploads/2018/08/Tam-Coc-Boat-Ride.jpg", "Day 1: Explore Tam Coc caves and river, Day 2: Visit nearby rice fields", "Tam Coc Adventure Co.", 5),
("Ninh Binh Historical Tour", "Visit ancient temples and pagodas like Bai Dinh and Hoa Lu on this full-day tour to explore Ninh Binh\'s rich history.", "2024-12-23", "2024-12-26", 6000000, "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/29/9e/f5/69/caption.jpg?w=500&h=400&s=1", "Day 1: Bai Dinh Pagoda, Day 2: Hoa Lu Ancient Capital", "Ninh Binh Heritage Tours", 5),
("Trang An Eco Tour", "A boat trip through the UNESCO-listed Trang An Scenic Landscape, featuring caves, grottoes, and lush landscapes.", "2024-12-25", "2024-12-28", 7000000, "https://daytourshanoi.com/wp-content/uploads/trang-an-boat-trip-2.jpg", "Day 1: Boat ride through Trang An, Day 2: Visit scenic grottoes", "Trang An Eco Travel", 5),
("Ha Giang Motorbike Adventure", "A 5-day motorbike tour along the Dong Van Karst Plateau, exploring remote villages and breathtaking landscapes.", "2024-12-20", "2024-12-24", 15000000, "https://media.vietnammotorcycletours.com/storage/2022/12/ha-giang-loop-motorbike-8.jpg", "Day 1-5: Ride through the Dong Van Plateau and visit local villages", "Ha Giang Adventure Rides", 6),
("Ha Giang Ethnic Markets Tour", "Visit Ha Giang\'s vibrant ethnic markets and experience the unique culture and traditions of the local tribes.", "2024-12-20", "2024-12-27", 5000000, "https://saigontourist.net/uploads/destination/TrongNuoc/mienbac/sapa/sapa-market.jpg", "Day 1: Dong Van Market, Day 2: Local villages and cultural events", "Ha Giang Cultural Experiences", 6),
("Ha Giang Trekking Tour", "Embark on a trekking adventure through the picturesque hills and valleys of Ha Giang, perfect for nature lovers and photographers.", "2024-12-02", "2024-12-07", 8000000, "https://www.mrlinhadventure.com/UserFiles/Image/Gallerytour/trekking%20in%20remote%20north%20Vietnam13.jpg", "Day 1-5: Trek through hills and valleys, Visit scenic viewpoints", "Ha Giang Trekking Tours", 6),
("Hue Imperial Citadel Tour", "A historical tour exploring the ancient Imperial City, the Royal Tombs, and the famous Perfume River.", "2024-12-22", "2024-12-27", 6000000, "https://www.deluxegrouptours.vn/wp-content/uploads/2023/07/Dai-Noi-Hue-2.jpg", "Day 1: Imperial City, Day 2: Royal Tombs and Perfume River", "Hue Heritage Travel", 10),
("Hue River Cruise", "Relax on a peaceful cruise along the Perfume River and visit the iconic Thien Mu Pagoda, a must-see landmark in Hue.", "2024-12-20", "2024-12-25", 4000000, "https://i.ytimg.com/vi/doltFP1L90U/maxresdefault.jpg", "Day 1: Perfume River cruise, Day 2: Visit Thien Mu Pagoda", "Hue River Adventures", 10),
("Hue Culinary Tour", "Taste the best of Hue\'s royal cuisine, including specialties like Bun Bo Hue and delicious local street food.", "2024-12-25", "2024-12-29", 3500000, "https://res-tour.com/wp-content/uploads/2020/11/am-thuc-hue.jpg", "Day 1: Royal cuisine, Day 2: Explore local street food markets", "Hue Food Trails", 10),
("Phong Nha Cave Exploration", "Explore the world\'s largest cave, Son Doong, and other stunning caves in Phong Nha-Ke Bang National Park.", "2024-12-20", "2024-12-26", 12000000, "https://www.explorevietnam.com.vn/phong-nha/wp-content/uploads/2020/05/Phong-Nha-cave.jpg", "Day 1: Son Doong Cave, Day 2: Explore other caves in the park", "Phong Nha Adventures", 11),
("Phong Nha Eco Trekking", "A day of trekking through Phong Nha\'s lush national park, discovering waterfalls, caves, and unique karst landscapes.", "2024-12-22", "2024-12-25", 7000000, "https://localvietnam.com/wp-content/uploads/2021/04/phong-nha-jungle-trekking-1024x684.jpg", "Day 1: Jungle trek, Day 2: Discover waterfalls and caves", "Eco Trek Phong Nha", 11),
("Phong Nha Village Homestay", "Stay with a local family in Phong Nha and learn about the traditional ways of life in this beautiful region.", "2024-12-22", "2024-12-28", 5000000, "https://mrvivu.com/wp-content/uploads/2022/04/jungle-boss-homestay.jpeg", "Day 1-3: Homestay experience with local culture", "Phong Nha Homestay Co.", 11),
("Da Lat Flower Garden Tour", "Explore the beautiful flower gardens in Da Lat, known for its vibrant colors and diverse plant species.", "2024-12-21", "2024-12-26", 4500000, "https://kimtravel.com/wp-content/uploads/2018/05/Traveling-Dalat-during-flower-seasons-1-e1525684227910.jpg", "Day 1: Visit multiple flower gardens, Day 2: Explore Da Lat\'s nature", "Da Lat Floral Adventures", 12),
("Da Lat Adventure Sports", "Experience adventure sports like canyoning, rock climbing, and hiking in the cool mountain air of Da Lat.", "2024-12-20", "2024-12-24", 8000000, "https://res.klook.com/image/upload/q_85/c_fill,w_563/activities/luqxj8nh0mokud1xul6h.jpg", "Day 1: Canyoning, Day 2: Rock climbing and hiking", "Da Lat Adventure Club", 12),
("Da Lat French Architecture Tour", "Discover the French colonial heritage of Da Lat with a guided tour of its charming villas and unique architecture.", "2024-12-23", "2024-12-27", 5000000, "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/08/e6/8b/e7/the-french-quarter.jpg?w=900&h=-1&s=1", "Day 1: Guided tour of French villas and landmarks", "Da Lat Heritage Walks", 12),
("Phu Yen Coastal Tour", "Explore the untouched beaches, rugged cliffs, and the stunning Da Dia Reef in Phu Yen, a hidden gem for beach lovers.", "2024-12-22", "2024-12-26", 4000000, "https://dulichtuoitreviet.vn/image/cache/catalog/tai-moi/1412/phu-yen-0x0.jpg", "Day 1: Da Dia Reef, Day 2: Scenic coastal drives", "Phu Yen Coastal Explorers", 13),
("Phu Yen Nature Trekking", "Trek through the natural beauty of Phu Yen, with its serene forests, mountains, and waterfalls.", "2024-12-25", "2024-12-29", 6000000, "https://vietnamoriginal-travel.com/upload/images/phu-yen-vietnam-robinson-island-Hoang-Minh-Duc.jpg", "Day 1: Guided trekking through forests and mountains", "Phu Yen Trekking Tours", 13),
("Phu Yen Cultural Tour", "Learn about the culture and traditions of the Cham people, including visits to ancient temples and local markets in Phu Yen.", "2024-12-24", "2024-12-28", 4500000, "https://r-xx.bstatic.com/xdata/images/city/608x352/885864.webp?k=f96b8d01cd213b12f7fc232e37eb3870e881b68d22f57f87f3b487361255da34&o=", "Day 1: Visit Cham temples, Day 2: Explore local markets", "Phu Yen Culture Guides", 13),
("Ho Chi Minh City Historical Tour", "A guided tour of the War Remnants Museum, Cu Chi Tunnels, and other landmarks highlighting Vietnam\'s modern history.", "2024-12-20", "2024-12-22", 7000000, "https://cdn.getyourguide.com/img/tour/abf315fc94a8cbb16fe572dff87c84d01ba9928a04c8e14043abfcc4ac90aeb0.jpg/146.jpg", "Evening: Cruise along Saigon River, Night: Dinner on board with live music","Saigon Cruise Co.", 14),
("Ho Chi Minh City Nightlife Tour", "Experience the bustling nightlife of Ho Chi Minh City with a tour through the city\'s top bars, clubs, and street food stalls.", "2024-12-25", "2024-12-28", 3000000, "https://www.travelvietnam.com/images/things-do-do/ho-chi-minh-city/nguyen-hue-walking-street_07672.jpg","Day 1: Arrival and Mekong Delta cruise, Day 2: Cultural and local cuisine experience","Southern Adventure Travel", 14),
("Ho Chi Minh City Shopping Tour", "Shop for souvenirs and local goods at the famous Ben Thanh Market and surrounding areas in Ho Chi Minh City.", "2024-12-22", "2024-12-28", 3500000, "https://cdn.antoursvietnam.com/wp-content/uploads/2023/07/Shopping-in-Ho-Chi-Minh-City-AN-Tours-Vietnam.png", "Morning: Notre Dame Cathedral and Post Office, Afternoon: War Remnants Museum and shopping at Ben Thanh Market","Ho Chi Minh City Tours", 14),
("Binh Thuan Cultural Heritage Tour", "Explore the cultural heritage of Binh Thuan, including the Cham ethnic culture and their ancient temples and ruins.", "2024-12-20", "2024-12-25", 4000000, "https://made-in-vietnam.com.vn/upload/product/unnamed-1-3844.jpg", "Day 1: Visit ancient Cham temples, Day 2: Explore local cultural sites and traditional crafts", "Binh Thuan Heritage Guides", 15),
("Binh Thuan Dragon Fruit Farm Tour", "Tour the famous dragon fruit plantations of Binh Thuan and learn about the cultivation of this exotic fruit.", "2024-12-25", "2024-12-28", 3500000, "https://statics.vinpearl.com/con-dao-snorkeling-05_1689345647.jpg", "Day 1: Farm visit and workshop, Day 2: Explore plantation techniques and tasting sessions", "Binh Thuan Agricultural Adventures", 15),
("Con Dao Island History Tour", "Visit the historic Con Dao Prison and learn about Vietnam\'s colonial past and revolutionary struggles.", "2024-12-20", "2024-12-24", 5000000, "https://dulichnhatrang24h.com/uploads/album/album_1604476456.jpg", "Day 1: Visit Con Dao prison and pier, Day 2: Explore Dam Trau beach and Hang Duong cemetery", "Con Dao Travel Co." , 16),
("Con Dao Beach Tour", "Relax and unwind on the unspoiled beaches of Con Dao, with time for swimming, sunbathing, and exploring the island\'s natural beauty.", "2024-12-23", "2024-12-27", 4000000, "https://localvietnam.com/wp-content/uploads/2021/05/con-dao-island-hopping-2-1024x683.jpg", "Day 1: Trekking through Con Dao National Park, Day 2: Scuba diving and coral reef exploration", "EcoConDao Tours", 16),
("Phu Quoc Snorkeling and Diving", "Enjoy a day of snorkeling or diving in the crystal-clear waters of Phu Quoc, home to diverse marine life and coral reefs.", "2024-12-25", "2024-12-28", 10000000, "https://statics.vinpearl.com/phu-quoc-snorkeling-06_1692678187.jpg","Day 1: Discover VinWonders, Day 2: Explore Hon Thom by cable car and An Thoi islands","Phu Quoc Travel Group", 17),
("Can Tho Floating Market Tour", "A half-day boat tour through the famous Cai Rang Floating Market, experiencing life on the Mekong River.", "2024-12-22", "2024-12-27", 3000000, "https://canthorivertour.com/upload/admin/maphome.jpg","Day 1: Visit Ong Pagoda and Can Tho Museum, Day 2: Boat ride through small canals and fruit tasting","Discover Can Tho", 18),
("Can Tho Orchard Visit", "Visit the lush fruit orchards in Can Tho and enjoy fresh local fruits in this peaceful rural setting.", "2024-12-25", "2024-12-28", 2500000, "https://www.cantho.gov.vn/wps/wcm/connect/4f83e1f2-a531-48d2-930a-1149f8ce3e2f/5/6.jpg?MOD=AJPERES&CACHEID=4f83e1f2-a531-48d2-930a-1149f8ce3e2f/5","Day 1: Visit fish sauce factories, Day 2: Snorkeling at Bai Sao and diving at Hon May Rut","Sea Explorer Co." , 18),
("Can Tho Rural Exploration", "Discover the charming rural life of the Mekong Delta with a tour of local villages, farms, and tranquil waterways.", "2024-12-23", "2024-12-28", 3500000, "https://hieutour.com/public/upload/images/hinhsanpham/2-day-can-tho-rural-life---hib2dcc1-16791675504987.JPG", "Day 1: Night market exploration, Day 2: Relaxing at Long Beach and visiting Phu Quoc prison","Paradise Phu Quoc", 18),
("Da Nang City Highlights", "A full-day tour of Da Nang\'s must-see sights, including the Marble Mountains, the Dragon Bridge, and My Khe Beach.", "2024-12-22", "2024-12-26", 6000000, "https://touringhighlights.com/wp-content/uploads/2020/07/Cau-Rong-Dragon-Bridge-Da-Nang-Vietnam.jpg", "Day 1: Visit Marble Mountains, Day 2: Explore My Khe Beach and Dragon Bridge", "Da Nang Explore Tours", 7),
("Bana Hills and Golden Bridge", "A scenic tour to Bana Hills to see the famous Golden Bridge, featuring spectacular views and cultural experiences.", "2024-12-25", "2024-12-28", 8000000, "https://vmtravel.com.vn/wp-content/uploads/2022/06/Golden_Bridge.jpg", "Day 1: Scenic cable car ride, Day 2: Explore Golden Bridge and Bana Hills attractions", "Bana Hills Scenic Journeys", 7),
("Da Nang Street Food Tour", "Discover the best of Da Nang\'s street food scene, from grilled seafood to local specialties like Mi Quang and banh xeo.", "2024-12-01", "2024-12-07", 4000000, "https://media.tacdn.com/media/attractions-splice-spp-674x446/08/a6/f8/90.jpg", "Evening tour: Visit multiple street food stalls and enjoy local dishes", "Da Nang Foodie Trails", 7),
("Hoi An Ancient Town Tour", "Explore the UNESCO World Heritage Site of Hoi An, including its lantern-lit streets, ancient houses, and the famous Japanese Covered Bridge.", "2024-12-23", "2024-12-26", 5000000, "https://vmtravel.com.vn/wp-content/uploads/2022/08/Hue-to-hoi-an.jpg", "Day 1: Visit historic sites, Day 2: Explore lantern-lit streets in the evening", "Hoi An Heritage Walks", 8),
("Hoi An Lantern Festival Tour", "Experience Hoi An\'s magical Lantern Festival, where the town is illuminated by colorful lanterns in celebration of traditional customs.", "2024-12-25", "2024-12-28", 6000000, "https://vietnamtour.in/wp-content/uploads/Hoi-An-Lantern-Festival-800x800.png", "Festival night: Lantern releasing and cultural performances", "Hoi An Festival Guides", 8),
("Hoi An Cooking Class", "Learn how to prepare traditional Vietnamese dishes in a hands-on cooking class, guided by expert local chefs.", "2024-12-01", "2024-12-05", 4500000, "https://cdn.antoursvietnam.com/wp-content/uploads/2023/08/Hoi-An-Cooking-Class-Taste-of-Vietnamese-home-6.webp", "Morning class: Visit local market, Afternoon: Cooking session with tasting", "Hoi An Culinary Experts", 8),
("Nha Trang Beach Tour", "Relax and enjoy the turquoise waters and sandy beaches of Nha Trang on this full-day beach tour.", "2024-12-20", "2024-12-25", 4000000, "https://www.vietnam-tour.biz/wp-content/uploads/2022/02/Nha-Trang-beach-tour-operators-in-Vietnam.png", "Day tour: Relaxation and leisure activities at Nha Trang beach", "Nha Trang Coastal Adventures", 9),
("Nha Trang Coral Reef Snorkeling", "Explore the vibrant coral reefs of Nha Trang with a guided snorkeling tour to see marine life up close.", "2024-12-23", "2024-12-27", 7000000, "https://www.nhatrangtouring.com/wp-content/uploads/2019/05/watch-colorful-coral-world.jpg", "Day 1: Snorkeling training, Day 2: Guided reef exploration", "Nha Trang Marine Tours", 9),
("Nha Trang City Tour", "Discover the city\'s top attractions including the Po Nagar Cham Towers, Long Son Pagoda, and Nha Trang Cathedral on a half-day tour.", "2024-12-23", "2024-12-26", 3000000, "https://dulichviet.com.vn/images/bandidau/review-lich-trinh-tham-quan-city-tour-nha-trang-cuc-hap-dan.png", "Half-day tour: Visit key landmarks and local attractions", "Nha Trang City Explorers", 9);

INSERT INTO users (email, username, password, fullname, phone, created_date) VALUES 
("john.doe@gmail.com.com", "johndoe123", "482c811da5d5b4bc6d497ffa98491e38", "John Doe", "0901234567", "2024-12-10"),
("jane.smith@gmail.com.com", "janesmith456", "fc5e038d38a57032085441e7fe7010b0", "Jane Smith", "0907654321", "2024-12-11"),
("alice.green@gmail.com.com", "alicegreen789", "e10adc3949ba59abbe56e057f20f883e", "Alice Green", "0918765432", "2024-12-12"),
("bob.johnson@gmail.com.com", "bobjohnson322", "ddac64383be2fdb7e5e9327723b8eab5", "Bob Johnson", "0918765432", "2024-12-13"),
("emily.white@gmail.com.com", "emilywhite567", "e80b5017098950fc58aad83c8c14978e", "Emily White", "0908765432", "2024-12-14"),
("michael.brown@gmail.com.com", "mikebrown88", "49729e2136d4e56ef822b5f9cfdb45b4", "Michael Brown", "0912348765", "2024-12-15");

INSERT INTO reviews (detail, rating, review_date, user_id) VALUES
("The tour was amazing! The guide was very knowledgeable, and the sights were beautiful. I especially loved the visit to the ancient temples. Highly recommended!", 5, "2024-12-10", 1),
("The hotel room was clean and spacious, but the staff could have been friendlier. Overall, a good stay, but there\'s room for improvement.", 3, "2024-12-11", 2),
("I had a fantastic time on the Ha Long Bay cruise. The scenery was breathtaking, and the boat crew were excellent. It\'s a perfect way to relax and enjoy nature.", 4, "2024-12-12", 3),
("The food at the restaurant was delicious, but the service was a bit slow. I had to wait a while for my order to arrive, which was a little frustrating.", 3, "2024-12-13", 1),
("The app is easy to use and very intuitive. It helped me plan my trip perfectly, and I had no issues navigating through it. Definitely will use it again for future travels!", 5, "2024-12-14", 5);

