<?php
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="css/main.css">
    <link rel="stylesheet" href="css/event.css" type="text/css">
    <!-- Link CSS của Swiper -->
    <link rel="stylesheet" href="https://unpkg.com/swiper/swiper-bundle.min.css">
    <title>CulturalLocation Page</title>
</head>
<body>
    <main>
        <!-- Header -->
        <div id="header-place">
            <?php require_once "view/components/header.php" ?>
        </div>

        <section>
            <div class="hero">
                <div class="heading">
                    <h1 class="heading-title" id="main-title">Explore Cultural Wonders</h1>
                    <p class="heading-description" id="main-description">
                        Discover unique cultures and beautiful destinations across the world.
                    </p>
                </div>
                <div class="hero-img">
                </div>
            </div>
        </section>

        <!-- Slider Section -->
        <section>
            <div class="slider">
                <div class="heading heading-section">
                    <h1 class="heading-title">Best Cultures</h1>
                    <p class="heading-description">Explore top cultural destinations.</p>
                </div>
                <div class="swiper mySwiper">
                    <div class="swiper-wrapper cards" id="slider-content">
                        <!-- Content will be dynamically generated by JavaScript -->
                    </div>
                </div>
            </div>
        </section>

        <!-- More Cultural Grid Section -->
        <section>
            <div class="more-cultural">
                <div class="heading heading-section">
                    <h1 class="heading-title">More Cultural Highlights</h1>
                    <p class="heading-description">Dive deeper into diverse cultures and traditions.</p>
                </div>
                <div class="more-cultural-grid" id="more-cultural-grid">
                    <!-- Content will be dynamically generated by JavaScript -->
                </div>
            </div>
        </section>

        <!-- Footer -->
        <?php require_once "view/components/footer.php" ?>
    </main>
    
   <!-- Swiper JS -->
    <script src="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.js"></script>
    <!-- Bootstrap JS -->
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
      crossorigin="anonymous"
    ></script>
    <!-- Link JS của Swiper -->
    <script src="https://unpkg.com/swiper/swiper-bundle.min.js"></script>
    <script src="scripts/culturalLocation.js" type="module"></script>
</body>
</html>
